import {ArrowRight,Check,CheckCircle2,Clock3,Leaf,ShieldCheck,Utensils,Flame,ArrowLeft,AlertCircle} from 'lucide-react';
import {useState} from 'react';
import {intent,money,modifierName,type Snapshot,type MenuItem,type VoiceIntent} from '../types';
import {confirmation} from '../state';

export function DishArt({item,small=false}:{item:MenuItem;small?:boolean}){
 const [failed,setFailed]=useState(false);
 return <div className={`dish-art ${item.id} ${small?'small':''}`}>
  {!failed?<img src={`/dishes/${item.id}.png`} alt={`${item.name}, illustrative dish photograph`} onError={()=>setFailed(true)}/>:<div className="plate-illustration"><span className="food one"/><span className="food two"/><span className="food three"/><span className="herb h1"/><span className="herb h2"/><span className="lemon"/></div>}
  <span className="photo-caption">Serving inspiration</span>
 </div>;
}
function Estimate({item}:{item:MenuItem}){return <span className={`estimate ${item.fits_preference?'':'slow'}`}><Clock3 size={14}/>{item.estimate_minutes===null?'Timing unknown':`~${item.estimate_minutes} min`}</span>;}
export default function DinerSurface({s,busy,onIntent}:{s:Snapshot;busy:boolean;onIntent:(i:VoiceIntent)=>void}){
 const modifiers=s.surface.modifiers??[];
 const mode=s.surface.mode;const selected=s.menu.find(i=>i.id===s.surface.item_ids[0])??s.menu[0];
 const reviewed=s.offer?.status==='pending'&&mode==='review';
 const order=s.order;
 const choose=(item:MenuItem)=>onIntent(intent('detail',{item_ids:[item.id]}));
 const review=(item:MenuItem)=>onIntent(intent('review',{item_ids:[item.id],modifiers:modifiers.filter(m=>item.modifiers.includes(m))}));
 if(reviewed&&s.offer){const offer=s.offer;return <section className="review-card surface-enter" aria-label="Review your order">
  <div className="review-heading"><span className="icon-circle"><Utensils size={22}/></span><span className="eyebrow">Your choice, your call</span><h2>A quick review.</h2><p>One more look before we send it to the kitchen.</p></div>
  <div className="review-dish"><div><h3>{offer.terms.name}</h3><p>1 serving · {offer.terms.modifiers.length?offer.terms.modifiers.map(modifierName).join(', '):'As the kitchen makes it'}</p></div><strong>{money(offer.terms.price_cents)}</strong></div>
  <div className="review-facts"><div><Clock3 size={18}/><span>Food ready in<strong>~{offer.terms.ready_in_minutes} minutes</strong></span></div><div><CheckCircle2 size={18}/><span>Your preference<strong>Within {offer.terms.ready_within_minutes} minutes</strong></span></div></div>
  <p className="quiet-note">Synthetic estimate from the service checkpoint. No payment is collected.</p>
  <button className="primary wide" disabled={busy} onClick={()=>onIntent(intent('confirm',confirmation(offer)))}>Confirm my order · {money(offer.terms.price_cents)}<ArrowRight size={17}/></button>
  <div className="review-secondary"><button disabled={busy} className="text-button" onClick={()=>onIntent(intent('detail',{item_ids:[selected.id],modifiers:offer.terms.modifiers as VoiceIntent['modifiers']}))}><ArrowLeft size={14}/> Make a change</button><button disabled={busy} className="text-button" onClick={()=>onIntent(intent('decline'))}>Not this time</button></div>
  <div className="consent-note"><ShieldCheck size={13}/>Nothing is reserved until you confirm.</div>
 </section>;}
 if(mode==='status'&&order){const done=order.status==='acknowledged';const failed=order.status==='failed';return <section className={`order-card surface-enter ${done?'complete':''}`} aria-label="Order status">
  <span className="order-seal">{done?<Check size={34}/>:failed?<AlertCircle size={32}/>:<Clock3 size={32}/>}</span>
  <span className="eyebrow">Table 07 · {done?'Kitchen acknowledged':failed?'Coordinator notified':'Awaiting the kitchen'}</span>
  <h2>{done?'You’re in good hands.':failed?'Let’s check with the kitchen.':'Your choice is on its way.'}</h2>
  <p>{s.surface.message}</p>
  <div className="order-receipt"><div><span>Your meal</span><strong>{order.terms.name}</strong><small>{order.terms.modifiers.length?order.terms.modifiers.map(modifierName).join(' · '):'Prepared as described'}</small></div><b>{money(order.terms.price_cents)}</b></div>
  <div className="order-progress"><span className="done"><CheckCircle2 size={17}/>You confirmed</span><i/><span className={done?'done':''}><CheckCircle2 size={17}/>Kitchen acknowledged</span><i/><span className={order.preparation_status==='started'||order.preparation_status==='ready'?'done':''}><Flame size={17}/>{order.preparation_status==='ready'?'Ready':'Preparing'}</span></div>
  <div className="ready-promise"><Clock3 size={18}/><span>{done?`Agreed food-ready estimate: ~${order.terms.ready_in_minutes} minutes`:'Your original confirmed terms remain visible.'}</span></div>
  <small className="quiet-note">Simulated kitchen · Synthetic timing · No payment collected</small>{failed&&<button className="secondary" style={{marginTop:18}} disabled={busy} onClick={()=>choose(selected)}>Choose again<ArrowRight size={15}/></button>}
 </section>;}
 if(mode==='clarify'||mode==='status'){return <section className="clarify-card surface-enter"><span className="icon-circle"><Utensils size={23}/></span><span className="eyebrow">Let’s get it right</span><h2>{s.diner.party_size===null?'Just you today?':'A little clarity helps.'}</h2><p>{s.surface.message}</p>{!s.diner.party_size?<button className="primary" disabled={busy} onClick={()=>onIntent(intent('preference',{party_size:1,item_ids:[selected.id]}))}>Yes, just me<ArrowRight size={16}/></button>:<button className="secondary" disabled={busy} onClick={()=>choose(s.menu[0])}>Back to the menu<ArrowRight size={16}/></button>}</section>;}
 if(mode==='compare'){const items=s.surface.item_ids.map(id=>s.menu.find(i=>i.id===id)!).filter(Boolean);return <section className="comparison surface-enter" aria-label="Compare your options"><div className="comparison-intro"><span className="eyebrow">A little flexibility, a good meal</span><h2>Let’s find your fit.</h2><p>{s.decision?.alternative_item_id?'The kitchen has an update. Here’s what it means for your meal.':s.surface.message}</p></div><div className="compare-grid">{items.map(item=><article className={`compare-card ${item.fits_preference?'fits':''}`} key={item.id}><DishArt item={item} small/><div className="compare-body"><div className="dish-kicker">{item.fits_preference?<><Leaf size={13}/>Fits your time</>:<><Clock3 size={13}/>A little longer</>}</div><h3>{item.name}</h3><div className="price-time"><strong>{money(item.price_cents)}</strong><Estimate item={item}/></div><p>{item.fits_preference?`Within your ${s.diner.ready_within_minutes}-minute preference.`:`Beyond your ${s.diner.ready_within_minutes}-minute preference.`}</p><button className={item.fits_preference?'primary wide':'secondary wide'} disabled={busy||item.stock===0} onClick={()=>item.fits_preference?review(item):choose(item)}>{item.stock===0?'Sold out':item.fits_preference?'Review this choice':'View dish'}<ArrowRight size={15}/></button></div></article>)}</div><div className="comparison-footer"><span>Synthetic food-ready estimates · Nothing reserved</span><button className="text-button" disabled={busy} onClick={()=>onIntent(intent('decline'))}>Neither works for me</button></div></section>;}
 return <section className="menu-surface surface-enter"><div className="dish-tabs" aria-label="Menu"><button className={selected.id==='chicken'?'active':''} disabled={busy} onClick={()=>choose(s.menu[0])}>From the grill</button><button className={selected.id==='mushroom'?'active':''} disabled={busy} onClick={()=>choose(s.menu[1])}>Plant-forward</button><button className={selected.id==='soup'?'active':''} disabled={busy} onClick={()=>choose(s.menu[2])}>Something light</button></div>
  <article className="hero-dish"><DishArt item={selected}/><div className="dish-info"><div className="dish-kicker">{selected.station==='grill'?<Flame size={14}/>:<Leaf size={14}/>} {selected.tags[0]}</div><h2>{selected.name}</h2><p className="dish-description">{selected.description}</p><div className="price-time"><strong>{money(selected.price_cents)}</strong><Estimate item={selected}/></div><p className={`fit-copy ${selected.fits_preference?'':'slow'}`}>{selected.stock===0?'This dish has sold out.':selected.fits_preference?`Fits your ${s.diner.ready_within_minutes}-minute preference.`:'The current kitchen plan needs a little more time.'}</p><div className="modifier-options">{selected.modifiers.map(m=><label key={m}><input type="checkbox" disabled={busy} checked={modifiers.includes(m as VoiceIntent['modifiers'][number])} onChange={e=>onIntent(intent('detail',{item_ids:[selected.id],modifiers:e.target.checked?[...modifiers,m as VoiceIntent['modifiers'][number]]:modifiers.filter(v=>v!==m)}))}/>{modifierName(m)}</label>)}</div><button className="primary wide" disabled={busy||selected.stock===0} onClick={()=>review(selected)}>{selected.stock===0?'Sold out':selected.fits_preference?'Review this dish':'Explore my options'}<ArrowRight size={17}/></button><small className="quiet-note">Synthetic food-ready estimate. Review before ordering.</small></div></article>
 </section>;
}
