import {Activity,ArrowRight,Check,CheckCircle2,ChevronDown,Clock3,Flame,Pause,Play,SlidersHorizontal,ShieldCheck,AlertCircle,RefreshCw} from 'lucide-react';
import {useState} from 'react';
import type {Snapshot} from '../types';
const time=(at:string)=>new Date(at).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});
export default function KitchenPanel({s,busy,onCommand}:{s:Snapshot;busy:boolean;onCommand:(kind:string,payload:object)=>void}){
 const [capacity,setCapacity]=useState('2');const [reason,setReason]=useState('Grill checked by coordinator; both slots available.');const [override,setOverride]=useState('');
 const decision=s.decision;const pending=s.actions.filter(a=>a.status==='requested');
 const grill=(ids:string[])=>ids.filter(id=>s.tickets.find(t=>t.id===id)?.station==='grill');
 const before=grill(decision?.before??s.active_sequence);const after=grill(decision?.after??s.active_sequence);
 const thinking=s.planner.status==='thinking';const latest=s.actions.at(-1);
 return <aside className="kitchen-panel" aria-label="Coordinator kitchen view"><div className="kitchen-header"><div><span className="eyebrow">Coordinator’s live view</span><h2>Kitchen, in sync.</h2></div><span className={`live-dot ${s.paused?'paused':''}`} title={s.paused?'Paused':'Live service'}/></div>
  <div className="agent-status"><span className={thinking?'spinning':''}>{thinking?<RefreshCw size={14}/>:s.paused?<Pause size={14}/>:<Activity size={14}/>}</span><strong>{thinking?'Considering the whole kitchen…':s.paused?'Autonomy paused':s.planner.status==='error'?'Coordinator attention needed':'Watching the whole service'}</strong><span className="version">v{s.state_version}</span></div>
  <div className={`capacity-card ${s.capacity.value!==2?'constrained':''}`}><div><Flame size={17}/><strong>{!s.capacity.fresh?'Capacity needs an update':s.capacity.value===2?'Grill running smoothly':`${s.capacity.value} grill slot${s.capacity.value===1?'':'s'} available`}</strong><span className="source-label">Simulated</span></div><p>{s.capacity.note}</p><small>{s.capacity.source_kind==='human_report'?'Cook report':s.capacity.source_kind==='unknown'?'Unknown':'Station record'} · {s.capacity.source_id.replaceAll('_',' ')} · {time(s.capacity.observed_at)}</small></div>
  <section className="commitments"><div className="section-label"><span>Confirmed commitments</span><span className={s.commitments_met===s.commitments_total?'good':'amber'}>{s.commitments_met}/{s.commitments_total} on track</span></div><div className="ticket-list">{s.tickets.map(t=>{const timing=s.timeline.find(x=>x.ticket_id===t.id);return <div className="ticket-row" key={t.id}><span className={`ticket-id ${t.status==='started'?'started':''}`}>{t.id}</span><div><strong>Table {t.table}<small>{t.name}</small></strong></div><span className="ticket-time">{t.status==='ready'?'Ready':`+${timing?.end??'?'} min`}<small>agreed +{t.ready_by}</small></span>{t.status==='ready'||timing?.on_time?<CheckCircle2 className="good" size={15}/>:<AlertCircle className="amber" size={15}/>}</div>;})}</div><small className="source-footnote">Seeded ticket records · C already started · Synthetic timing</small></section>
  <section className="sequence-section"><div className="section-label"><span>Grill preparation sequence</span><span>{decision?.status==='acknowledged'?'Active':decision?.status==='requested'?'Awaiting acknowledgment':'Current'}</span></div><div className="sequence-comparison"><div><small>Before</small><div>{before.map((id,i)=><span className="sequence-unit" key={id}>{i>0&&<ArrowRight size={11}/>}<b>{id}</b></span>)}</div></div><ArrowRight className="sequence-arrow" size={18}/><div className={decision?.status==='acknowledged'?'sequence-after active':'sequence-after'}><small>{decision?.model==='coordinator'?'Coordinator override':decision?'Agent’s decision':'Active plan'}</small><div>{after.map((id,i)=><span className="sequence-unit" key={id}>{i>0&&<ArrowRight size={11}/>}<b>{id}</b></span>)}</div></div></div>
  {decision?<details className="decision-rationale"><summary><ShieldCheck size={14}/>{decision.coordinator_question?'Coordinator input requested':'Commitments checked. Started work preserved.'}<ChevronDown size={13}/></summary><p>{decision.rationale}</p><small>{decision.model} · {time(decision.decided_at)} · {decision.model==='coordinator'?'Guarded override':'Derived proposal'}</small></details>:<p className="sequence-note">The agent can change preparation order. Meal choices stay with the diner.</p>}
  </section>
  <div className={`action-ack ${latest?.status??'idle'}`}><span>{latest?.status==='acknowledged'?<CheckCircle2 size={18}/>:latest?.status==='failed'?<AlertCircle size={18}/>:<Clock3 size={18}/>}</span><div><strong>{latest?latest.status==='acknowledged'?(latest.kind==='order'?'Order acknowledged':'Sequence acknowledged'):latest.status==='failed'?'Kitchen request failed':'Sent · awaiting kitchen':'Ready for the next moment'}</strong><small>{latest?'Kitchen simulator · '+(latest.acknowledged_at?time(latest.acknowledged_at):'request recorded'):'Actions become active only after acknowledgment.'}</small></div></div>
  {s.planner.status==='error'&&<div className="inline-alert" role="alert">{s.planner.message}<button className="text-button" disabled={busy} onClick={()=>onCommand('replan',{})}>Retry decision</button></div>}
  {s.exceptions.length>0&&<details className="exceptions"><summary><AlertCircle size={14}/>{s.exceptions.length} visible exception{s.exceptions.length>1?'s':''}<ChevronDown size={13}/></summary>{s.exceptions.map(e=><p key={e.id}>{e.message}</p>)}</details>}
  <div className="supervisor"><button className="secondary compact" disabled={busy} onClick={()=>onCommand('pause',{paused:!s.paused})}>{s.paused?<Play size={13}/>:<Pause size={13}/>} {s.paused?'Resume agent':'Pause agent'}</button><span>You’re in control.</span></div>
  <details className="controls"><summary><SlidersHorizontal size={14}/> Coordinator controls<ChevronDown size={13}/></summary><div className="controls-body"><label>Correct grill capacity<select value={capacity} onChange={e=>setCapacity(e.target.value)}><option value="2">2 slots</option><option value="1">1 slot</option><option value="0">0 slots</option><option value="unknown">Unknown — needs staff update</option></select></label><label>Source note<input value={reason} onChange={e=>setReason(e.target.value)} maxLength={240}/></label><button className="secondary wide" disabled={busy||!reason} onClick={()=>onCommand('report',{capacity:capacity==='unknown'?null:Number(capacity),source_id:'coordinator',source_kind:capacity==='unknown'?'unknown':'human_report',observed_at:new Date().toISOString(),simulated:true,note:reason})}>Apply source correction</button>
  <label>Override one sequence<input placeholder={`e.g. ${s.active_sequence.join(', ')}`} value={override} onChange={e=>setOverride(e.target.value)}/></label><button className="secondary wide" disabled={busy||!override} onClick={()=>onCommand('override',{sequence:override.split(',').map(v=>v.trim()).filter(Boolean),reason:'One-decision override by coordinator'})}>Request guarded override</button><label>Kitchen acknowledgment<select value={s.ack_mode} onChange={e=>onCommand('ack_mode',{mode:e.target.value})}><option value="auto">Automatic simulator acknowledgment</option><option value="manual">Hold for manual acknowledgment</option><option value="fail_next">Fail the next acknowledgment</option></select></label>{pending.map(a=><div className="pending-controls" key={a.id}><span>{a.kind} request</span><button disabled={busy} onClick={()=>onCommand('ack',{action_id:a.id,success:true})}><Check size={14}/>Acknowledge</button><button disabled={busy} onClick={()=>onCommand('ack',{action_id:a.id,success:false})}>Fail</button></div>)}<button className="text-button" disabled={busy} onClick={()=>onCommand('replan',{})}><RefreshCw size={13}/> Ask for a fresh decision</button>
  </div></details>
  <details className="event-log"><summary>Service activity<ChevronDown size={13}/></summary><ol>{s.events.slice().reverse().map(e=><li key={e.id}><span>{e.message}</span><small>{e.source_id.replaceAll('_',' ')} · {e.source_kind} {e.simulated?'· simulated':''} · {time(e.observed_at)}</small></li>)}</ol></details>
 </aside>;
}
